port: 5000
server_ip: 192.168.100.1
quorum_percent: 60

heartbeat_timeout: 120
watchdog_interval: 5

nids_control_ip: 192.168.100.254
nids_control_port: 5001

tls_ca_port: 5002

# debug: 0
tls_enable: 1
# Način donošenja odluke nakon NIDS alarma:
# correlated = NIDS + heartbeat + peer podaci + distribuirana potvrda
# nids_only  = samo NIDS detekcija; valjani ICMP flood vodi izravno prema BLOCK odluci
# Dopuštene vrijednosti: correlated, nids_only
response_mode: correlated
