id:         agent-01
server_ip:  192.168.100.1
server_port: 5000

iface: enp0s8
subnet: 192.168.100.0/24

debug: 0

intervals:
  heartbeat: 60
  status: 60
  latency: 60
  banner: 60      
  discovery: 60
  traffic: 3

traffic:
  sample_packets: 50
  threshold: 20
  window_seconds: 5

services:
  - name: nginx
    port: 80

peers:
  - 192.168.100.3   # agent-02
  - 192.168.100.4   # agent-03

tls:
  enable: 0
  ca: ./ssl/ca-cert.pem

banner:
  mode: all
  discovery: 1

